In [ ]:
# step1:- we have to import the dataset to the colab notebook.
import pandas as pd # pd is an instance of pandas
df =pd.read_csv('csv.csv')#df is a variable, read_csv is a predefined  function from  pandas package



In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [ ]:
#step2:-grouping the input colums and output colums
X=df.iloc[:,:-1]

In [ ]:
X

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [ ]:
y=df.iloc[:,-1]

In [ ]:
type(y)

pandas.core.series.Series

In [ ]:
X=X.values

In [ ]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [ ]:
y=y.values

In [ ]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [ ]:
# step3:- handling missing data and nan values
#scenario-1:missing values from numeric values
#scenario-2:missing values from non numeric values
#scenario-3:missing values in huge data set

import numpy as np
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(X[:,1:3])
X[:,1:3]=imputer.transform(X[:,1:3])



In [ ]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [ ]:
# step:4-handling the catagorial data
# which converts the text data into numeric data
from sklearn.preprocessing import OneHotEncoder
#is a class which was imported from S1.preprocessing library
#is used to convert
from sklearn.compose import ColumnTransformer
#  is a class which was imported from
#is used to apply changes of numeric data from catagorial data

#Alexa-0,0,1
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')#is a method which converts to txt to binary
X=ct.fit_transform(X)

In [ ]:
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [ ]:
#one hot encoder is apply for only input colums
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

In [ ]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [ ]:
#step5:-split the data into training and testing data
from sklearn.model_selection import train_test_split
#is a class which was import from model_selection
#spliting the data into training and testing
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [ ]:
X_train

array([[0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0]], dtype=object)

In [ ]:
X_test

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778]], dtype=object)

In [ ]:
y_train

array([0, 0, 0, 1, 0, 1, 1, 1])

In [ ]:
y_test

array([0, 1])

In [ ]:
#step6:-feature scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

X_train[:,3:]=sc.fit_transform(X_train[:,3:])
X_test[:,3:]=sc.transform (X_test[:,3:])

In [ ]:
X_test

array([[1.0, 0.0, 0.0, 0.8131562315694638, 0.7791632330139234],
       [0.0, 1.0, 0.0, 0.27355025301645564, 0.08657369255710287]],
      dtype=object)

In [ ]:
X_train

array([[0.0, 0.0, 1.0, 0.10867064845859215, -0.9055140275567218],
       [0.0, 1.0, 0.0, 1.622565199398976, 1.7057357263277784],
       [0.0, 0.0, 1.0, 0.003747263739951552, -0.14740926029993145],
       [1.0, 0.0, 0.0, 1.352762210122472, 1.3688002742136494],
       [0.0, 1.0, 0.0, -1.0754646933660648, -0.7370463014996573],
       [0.0, 0.0, 1.0, -1.480169177280821, -1.242449479670851],
       [1.0, 0.0, 0.0, -0.1311542308983005, 0.3579939178712621],
       [1.0, 0.0, 0.0, -0.4009572201748046, -0.40011084938552827]],
      dtype=object)

In [ ]:
#machine learning having 3 types
#1.supervised learning-when we have a labled data,the model tasks are classification or prediction
#2.unsupervised learning-unlabled data,model remembers the patterns,we can perform predictions also.
#3.reinforcement learning-model learn from failures or trail and error method


In [ ]:
#logistic regression algorithm
#when model performs prediction task we have to  apply linear regression algorithm
#linear regression algorithm :prediction we use it

In [ ]:
#step7:-apply algorithm to  the training data for model
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression()
classifier.fit(X_train,y_train)

LogisticRegression()

In [ ]:
y_pred=classifier.predict(X_test)

In [ ]:
y_pred

array([1, 0])